apiVersion: v1
kind: Service
metadata:
  name: yelb-db
spec:
  type: ExternalName
  externalName: {{.Values.postgresql.master_ip | default "yelb-db"}}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 6432
