apiVersion: v1
kind: Service
metadata:
  name: yelb-appserver
  labels:
    app: yelb-appserver
spec:
  type: ClusterIP
  ports:
    - port: 4567
  selector:
    app: yelb-appserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-appserver
spec:
  replicas: {{ .Values.app.replicaCount | default 1}}
  selector:
    matchLabels:
      app: yelb-appserver
  template:
    metadata:
      labels:
        app: yelb-appserver
    spec:
      containers:
        - name: yelb-appserver
          image:  "{{.Values.image.repository}}/{{.Values.app.image}}:{{.Values.app.tag| default "latest"}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: 4567
          envFrom:
            - configMapRef:
                name: env