apiVersion: v2
name: yelb
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: ingress-nginx
    version: "4.1.4"
    repository: https://kubernetes.github.io/ingress-nginx