app:
  replicaCount: 2
  image: yelb-appserver
  tag: latest

image:
  repository: cr.yandex/${TF_VAR_yc_registry_id}
  pullPolicy: Always

imagePullSecrets: []

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  defaultBackend:
    address: yelb-appserver
    name: yelb-appserver
    host: yelb-appserver
    port: 4587
  path: /
  hosts:
    - api.s041120.tech

### Use reserved IP from Terraform state.
ingress-nginx:
  controller:
    service:
      loadBalancerIP: ${TF_VAR_LB_IP}

### Postgresql_managed Master IP for yelb.db
postgresql:
  master_ip: ${TF_VAR_pg_host}

env_configmap:
  values:
    YELB_DB_NAME: ${TF_VAR_pg_dbname}
    YELB_DB_USER: ${TF_VAR_pg_user}
    YELB_DB_PASSWORD: ${TF_VAR_pg_password}
    YELB_DB_PORT: "6432"
